/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalknookAdminPanelRouteImport } from './routes/talknook-admin-panel'
import { Route as PeerSupportRouteImport } from './routes/peer-support'
import { Route as HealthNavigationRouteImport } from './routes/health-navigation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'

const TalknookAdminPanelRoute = TalknookAdminPanelRouteImport.update({
  id: '/talknook-admin-panel',
  path: '/talknook-admin-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PeerSupportRoute = PeerSupportRouteImport.update({
  id: '/peer-support',
  path: '/peer-support',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthNavigationRoute = HealthNavigationRouteImport.update({
  id: '/health-navigation',
  path: '/health-navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/health-navigation': typeof HealthNavigationRoute
  '/peer-support': typeof PeerSupportRoute
  '/talknook-admin-panel': typeof TalknookAdminPanelRoute
  '/chat/$chatId': typeof ChatChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/health-navigation': typeof HealthNavigationRoute
  '/peer-support': typeof PeerSupportRoute
  '/talknook-admin-panel': typeof TalknookAdminPanelRoute
  '/chat/$chatId': typeof ChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/health-navigation': typeof HealthNavigationRoute
  '/peer-support': typeof PeerSupportRoute
  '/talknook-admin-panel': typeof TalknookAdminPanelRoute
  '/chat/$chatId': typeof ChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/health-navigation'
    | '/peer-support'
    | '/talknook-admin-panel'
    | '/chat/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/health-navigation'
    | '/peer-support'
    | '/talknook-admin-panel'
    | '/chat/$chatId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/health-navigation'
    | '/peer-support'
    | '/talknook-admin-panel'
    | '/chat/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  HealthNavigationRoute: typeof HealthNavigationRoute
  PeerSupportRoute: typeof PeerSupportRoute
  TalknookAdminPanelRoute: typeof TalknookAdminPanelRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talknook-admin-panel': {
      id: '/talknook-admin-panel'
      path: '/talknook-admin-panel'
      fullPath: '/talknook-admin-panel'
      preLoaderRoute: typeof TalknookAdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peer-support': {
      id: '/peer-support'
      path: '/peer-support'
      fullPath: '/peer-support'
      preLoaderRoute: typeof PeerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-navigation': {
      id: '/health-navigation'
      path: '/health-navigation'
      fullPath: '/health-navigation'
      preLoaderRoute: typeof HealthNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  HealthNavigationRoute: HealthNavigationRoute,
  PeerSupportRoute: PeerSupportRoute,
  TalknookAdminPanelRoute: TalknookAdminPanelRoute,
  ChatChatIdRoute: ChatChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
